### ISSUE TITLE
Possibility to avoid root access

### ISSUE THREAD

**Issue by TheCrazyLex** [nicholaschum/substratum#29] opened 2016-12-02 12:15 UTC
I wanted to ask whether there is any possibility to avoid the dependency of
Root access of this ( and the masquerade app). 

Some ROMs which don't want to ship with root access, may want to just preinstall
both apps as system apps (or as priviledged system apps), so I wanted to ask whether there
is any way or any plan to accomplish that in the future. 

My team and me are willing to help.

**Comment by kaluoshi** [comment] 2016-12-02 12:16
Subscribed

**Comment by nicholaschum** [comment] 2016-12-02 12:27
I have already begun the consolidation of most of the root commands, so that one day it may be easy to just replace the root commands within the References file.

https://github.com/nicholaschum/substratum/blob/dev/app/src/main/java/projekt/substratum/config/References.java#L814

However, not only do we have to take account for Substratum legacy, there are many commands like `rm -rf DIR` that are much quicker than the traditional `boolean deleted = file.delete()` with a recursive function, where in many cases the system may be using a file/permissions error to access a file so the file won't be deleted (files have been closed from access and it still happens). We also need access to /data/ partition, which requires root. This is where our files are placed.

The masquerade app is a helper application and must remain, due to the nature of windowRefreshes, when an app calls config change, the calling app will take on the responsibility to be a "tribute" to give up all it's resources first, then would work on reloading the other applications. So for example, if you trigger a configuration change on masquerade for substratum, all of masquerade's resources will be invalidated, and once invalidated, the command will refresh substratum - sort of like an alternative thread that is _more persistent_ than a Handler thread or an AsyncTask directly with substratum. Since substratum has many more resources to invalidate when it calls the configuration change, this ultimately means that if we have masquerade, substratum will not hang as long when applying a full theme - but if we call it directly from substratum without masquerade, then it would hang for a few seconds, a black screen, then the SystemUI restarts. 

This is all due to resource invalidation and alternative persistent threading. I'm completely down to the idea to getting root out, but I'll wait till I finish adding the features we need first.

**Comment by Sykopompos** [comment] 2016-12-02 16:50
As Nick said above there is a few things but we have started workimg towards removal of root.

Masquerade is a helper that can be a privledged system app with system permissions and can enable/disable overlays without root as long as it has the system change configuration permission.
Subs could call masquerade and let it handle that part no problem and was the intention going forward working out root.

The problem is the installation of overlays.
Yes we can have permissions to install and remove packages but the issue lies with that we can't do them silently so the user would have to go through the prompts for 25+ overlay installations which would not be user friendly so thats the major hurdle for non root use.

Probably rolling our own package installer might be a technical feasible way to do it, other possible options is like Samsung does and use a script method to batch install.

Or probably the most feasible option but the most work would be to change how the system sees the overlays more similar to like cmte does and avoid the installation process altogether and not even have to do with package signing either significantly speeding up the whole installation process so it would be a two birds one stone deal.

**Comment by sooorajjj** [comment] 2017-01-13 05:55
Hello all , 
In my personal project , i had similar issues of permissions even after making the app as system priv-app.
it would still ask for permissions and not grant them by default .
So the workaround for this was 

1. Adding system id in manifest : android:sharedUserId="android.uid.system"
2. Signing apk with platform keys
3. Integrating that apk with our source code as priv app by keeping apk in priv-app folder and adding same in Android.mk and device-vendor.mk
4. Building source code and signing the build with platform keys

But at this point GTS DefaultGrant test was getting failed and user was also able to toggle ON/OFF the permissions from the settings.

Later we made few changes in the DefaultPermissionGrantPolicy.java file , now permissions were granted , user was not able to toggle OFF/ON and they were not visible.
So making changes to DefaultPermissionGrantPolicy as per your requirements , will help you overcome the issue of accepting prompts for 25+ overlay installations (These permissions will be already available or the app ).
The only problem we have now is  GTS defaultgrant test gets failed.

**Comment by sooorajjj** [comment] 2017-01-13 06:05
To pass GTS Google has suggested us not to edit [DefaultPermissionGrantPolicy](https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/pm/DefaultPermissionGrantPolicy.java)

> You must configure and install the app so that it passed without changing the rules. I suggest that you read the default permission grant policy code and configure you app accordingly. 
> 
> The following packages for example are privileged system applications that are not subject to runtime permission rules:
> 
>    * frameworks/base/packages/SystemUI
>    * packages/services/Telephony
> 
> For you application to have a fixed permission the permission must have the following flag, "PackageManager.FLAG_PERMISSION_SYSTEM_FIXED"

We never got it to meet our requirements without Making changes to DefaultPermissionGrantPolicy.
If you guys are somehow able to get this worked out(Get it GTS pass and provide DefaultPermissionGrant ) , please let us know too :)

**Comment by sooorajjj** [comment] 2017-01-13 09:15
Ohk finally we manged to fix it we moved 
android:sharedUserId="android.uid.system" from application tag to manifest tag and it all works now , no need to edit DefaultPermissionGrantPolicy.

**Comment by nicholaschum** [comment] 2017-02-14 05:17
@TheCrazyLex @carlosavignano @Thecrazyskull 

Rootless is complete. Undergoing testing now. Closing this Issue now as upstream dev branch has all rootless commits in!

**Closed as completed by nicholaschum** 2017-02-14 05:17 UTC
